extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
plugins:
  - "@typescript-eslint"
  - "prettier"

env:
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: "./tsconfig.json"
rules:
  semi: error
  node/no-missing-import: error
  prettier/prettier: error
  quotes:
    - warn
    - single
    - double
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
    - ignore-pattern: "^_"
  "@typescript-eslint/no-unused-vars": ["error"]
